version: '2'
services:
  web: &APP_CONFIG
    build:
      context: .
    links:
      - postgres
      - redis
    environment: &APP_ENVIRONMENT
      DATABASE_URL: postgres://postgres@postgres:5432/
      REDIS_URL: redis://redis:6379
      VIRTUAL_HOST: panda-team.docker
    volumes:
      - gems:/home/docker/.gem/ruby/2.3.0

  postgres:
    image: postgres:9.3
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:2.8
    volumes:
      - redis_data:/data

volumes:
  gems: {}
  pg_data: {}
  redis_data: {}
  s3_data: {}
